[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_cuneiform_anchor = "BJKrKzXX4YfEYMZaVT2dbuaNuq7aqN3Xmib27JLALs3M"

[programs.devnet]
solana_cuneiform_anchor = "BJKrKzXX4YfEYMZaVT2dbuaNuq7aqN3Xmib27JLALs3M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-node tests/solana-cuneiform-anchor.ts"
