[package]
name = "solana-cuneiform-anchor"
version = "0.1.0"
description = "Solana program for registering Cuneiform-U semantic coordinates"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_cuneiform_anchor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
