// Copyright © 2026 Zymatica
// SPDX-License-Identifier: LicenseRef-Zymatica-Covenant-2.0
// See LICENSE for terms.

// ============================================================================
// ZK-LoRaWAN FFI Library — Hardened Groth16 BN254 Verifier
// ============================================================================
// Uses file-persisted keys generated by OsRng (no deterministic seed).
// Verifies 8 public inputs: identity, nullifier, attestation, ciphertext,
// gateway (2), deposit_commitment, firmware_hash.
// ============================================================================

pub mod circuit;

use ark_ff::PrimeField;
use ark_serialize::CanonicalDeserialize;
use std::path::Path;
use std::sync::OnceLock;

static PREPARED_VK: OnceLock<Result<ark_groth16::PreparedVerifyingKey<ark_bn254::Bn254>, String>> =
    OnceLock::new();

const VK_FILE: &str = "keys/verifying_key.bin";

/// Load the exact production verifying key. Verification fails closed if the key is missing,
/// corrupt, or belongs to a different ceremony. A verifier must never silently generate a new
/// key because that creates a statement domain incompatible with previously issued proofs.
fn load_vk_from_path(
    path: &Path,
) -> Result<ark_groth16::PreparedVerifyingKey<ark_bn254::Bn254>, String> {
    let vk_data = std::fs::read(path)
        .map_err(|error| format!("failed to read verifying key {}: {error}", path.display()))?;
    let vk = ark_groth16::VerifyingKey::<ark_bn254::Bn254>::deserialize_compressed(&vk_data[..])
        .map_err(|error| format!("invalid verifying key {}: {error}", path.display()))?;
    Ok(ark_groth16::prepare_verifying_key(&vk))
}

fn load_production_vk() -> Result<ark_groth16::PreparedVerifyingKey<ark_bn254::Bn254>, String> {
    load_vk_from_path(Path::new(VK_FILE))
}

/// FFI verification function.
/// Takes hex strings for proof points, public input hashes, gateway address,
/// deposit_value, and firmware_hash. Returns 1 for valid, 0 for invalid.
///
/// # Safety
///
/// All pointer/length pairs must point to readable UTF-8 byte buffers.
#[no_mangle]
#[allow(clippy::too_many_arguments)]
pub unsafe extern "C" fn verify_zk_proof_raw(
    proof_a_hex_ptr: *const u8,
    proof_a_hex_len: usize,
    proof_b_hex_ptr: *const u8,
    proof_b_hex_len: usize,
    proof_c_hex_ptr: *const u8,
    proof_c_hex_len: usize,
    identity_hash_hex_ptr: *const u8,
    identity_hash_hex_len: usize,
    nullifier_hash_hex_ptr: *const u8,
    nullifier_hash_hex_len: usize,
    attestation_hash_hex_ptr: *const u8,
    attestation_hash_hex_len: usize,
    ciphertext_hash_hex_ptr: *const u8,
    ciphertext_hash_hex_len: usize,
    gateway_address_hex_ptr: *const u8,
    gateway_address_hex_len: usize,
    deposit_value: u64,
    firmware_hash_hex_ptr: *const u8,
    firmware_hash_hex_len: usize,
) -> u32 {
    let proof_a_bytes_slice =
        unsafe { std::slice::from_raw_parts(proof_a_hex_ptr, proof_a_hex_len) };
    let proof_b_bytes_slice =
        unsafe { std::slice::from_raw_parts(proof_b_hex_ptr, proof_b_hex_len) };
    let proof_c_bytes_slice =
        unsafe { std::slice::from_raw_parts(proof_c_hex_ptr, proof_c_hex_len) };
    let identity_hash_bytes_slice =
        unsafe { std::slice::from_raw_parts(identity_hash_hex_ptr, identity_hash_hex_len) };
    let nullifier_hash_bytes_slice =
        unsafe { std::slice::from_raw_parts(nullifier_hash_hex_ptr, nullifier_hash_hex_len) };
    let attestation_hash_bytes_slice =
        unsafe { std::slice::from_raw_parts(attestation_hash_hex_ptr, attestation_hash_hex_len) };
    let ciphertext_hash_bytes_slice =
        unsafe { std::slice::from_raw_parts(ciphertext_hash_hex_ptr, ciphertext_hash_hex_len) };
    let gateway_address_bytes_slice =
        unsafe { std::slice::from_raw_parts(gateway_address_hex_ptr, gateway_address_hex_len) };
    let firmware_hash_bytes_slice =
        unsafe { std::slice::from_raw_parts(firmware_hash_hex_ptr, firmware_hash_hex_len) };

    let proof_a_str = match std::str::from_utf8(proof_a_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let proof_b_str = match std::str::from_utf8(proof_b_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let proof_c_str = match std::str::from_utf8(proof_c_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let identity_hash_str = match std::str::from_utf8(identity_hash_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let nullifier_hash_str = match std::str::from_utf8(nullifier_hash_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let attestation_hash_str = match std::str::from_utf8(attestation_hash_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let gateway_address_str = match std::str::from_utf8(gateway_address_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let ciphertext_hash_str = match std::str::from_utf8(ciphertext_hash_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let firmware_hash_str = match std::str::from_utf8(firmware_hash_bytes_slice) {
        Ok(s) => s,
        Err(_) => return 0,
    };

    let a_hex = proof_a_str.strip_prefix("0x").unwrap_or(proof_a_str);
    let b_hex = proof_b_str.strip_prefix("0x").unwrap_or(proof_b_str);
    let c_hex = proof_c_str.strip_prefix("0x").unwrap_or(proof_c_str);

    let proof_a_bytes = match hex::decode(a_hex) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let proof_b_bytes = match hex::decode(b_hex) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let proof_c_bytes = match hex::decode(c_hex) {
        Ok(b) => b,
        Err(_) => return 0,
    };

    let identity_bytes = match hex::decode(identity_hash_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let nullifier_bytes = match hex::decode(nullifier_hash_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let attestation_bytes = match hex::decode(attestation_hash_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let ciphertext_bytes = match hex::decode(ciphertext_hash_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    let gateway_address_bytes = match hex::decode(gateway_address_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };
    if gateway_address_bytes.len() != 32 {
        return 0;
    }
    let firmware_hash_bytes = match hex::decode(firmware_hash_str) {
        Ok(b) => b,
        Err(_) => return 0,
    };

    let proof_a = match ark_bn254::G1Affine::deserialize_compressed(&*proof_a_bytes) {
        Ok(p) => p,
        Err(_) => return 0,
    };
    let proof_b = match ark_bn254::G2Affine::deserialize_compressed(&*proof_b_bytes) {
        Ok(p) => p,
        Err(_) => return 0,
    };
    let proof_c = match ark_bn254::G1Affine::deserialize_compressed(&*proof_c_bytes) {
        Ok(p) => p,
        Err(_) => return 0,
    };

    let ark_proof = ark_groth16::Proof {
        a: proof_a,
        b: proof_b,
        c: proof_c,
    };

    let identity_hash_fr = match ark_bn254::Fr::deserialize_compressed(&*identity_bytes) {
        Ok(h) => h,
        Err(_) => return 0,
    };
    let nullifier_hash_fr = match ark_bn254::Fr::deserialize_compressed(&*nullifier_bytes) {
        Ok(h) => h,
        Err(_) => return 0,
    };
    let attestation_hash_fr = match ark_bn254::Fr::deserialize_compressed(&*attestation_bytes) {
        Ok(h) => h,
        Err(_) => return 0,
    };
    let ciphertext_hash_fr = match ark_bn254::Fr::deserialize_compressed(&*ciphertext_bytes) {
        Ok(h) => h,
        Err(_) => return 0,
    };

    let mut part1_bytes = [0u8; 32];
    part1_bytes[0..16].copy_from_slice(&gateway_address_bytes[0..16]);
    let gateway_part1_fr = match ark_bn254::Fr::deserialize_compressed(&part1_bytes[..]) {
        Ok(h) => h,
        Err(_) => return 0,
    };

    let mut part2_bytes = [0u8; 32];
    part2_bytes[0..16].copy_from_slice(&gateway_address_bytes[16..32]);
    let gateway_part2_fr = match ark_bn254::Fr::deserialize_compressed(&part2_bytes[..]) {
        Ok(h) => h,
        Err(_) => return 0,
    };

    // Compute deposit commitment and firmware hash Fr
    let deposit_value_fr = ark_bn254::Fr::from(deposit_value);
    let constants = circuit::generate_mimc_constants(220);
    let deposit_commitment =
        circuit::mimc_hash(identity_hash_fr, Some(deposit_value_fr), &constants);
    let firmware_hash_fr = ark_bn254::Fr::from_le_bytes_mod_order(&firmware_hash_bytes);

    // Fail closed when the expected production verifying key is absent/corrupt.
    let prepared_vk = match PREPARED_VK.get_or_init(load_production_vk) {
        Ok(vk) => vk,
        Err(error) => {
            eprintln!("ZK verification unavailable: {error}");
            return 0;
        }
    };

    match circuit::verify_proof(
        prepared_vk,
        &ark_proof,
        identity_hash_fr,
        nullifier_hash_fr,
        attestation_hash_fr,
        ciphertext_hash_fr,
        gateway_part1_fr,
        gateway_part2_fr,
        deposit_commitment,
        firmware_hash_fr,
    ) {
        Ok(true) => 1,
        _ => 0,
    }
}

fn to_solana_g1(p: &ark_bn254::G1Affine) -> [u8; 64] {
    use ark_ff::{BigInteger, PrimeField};

    let mut solana_bytes = [0u8; 64];
    solana_bytes[..32].copy_from_slice(&p.x.into_bigint().to_bytes_be());
    solana_bytes[32..].copy_from_slice(&p.y.into_bigint().to_bytes_be());
    solana_bytes
}

fn to_solana_g2(p: &ark_bn254::G2Affine) -> [u8; 128] {
    use ark_ff::{BigInteger, PrimeField};

    let mut solana_bytes = [0u8; 128];
    solana_bytes[..32].copy_from_slice(&p.x.c1.into_bigint().to_bytes_be());
    solana_bytes[32..64].copy_from_slice(&p.x.c0.into_bigint().to_bytes_be());
    solana_bytes[64..96].copy_from_slice(&p.y.c1.into_bigint().to_bytes_be());
    solana_bytes[96..].copy_from_slice(&p.y.c0.into_bigint().to_bytes_be());
    solana_bytes
}

/// Decodes compressed G1/G2 points and outputs uncompressed big-endian Solana coordinates.
///
/// # Safety
///
/// The compressed proof pointers must reference buffers of exactly 32, 64, and 32 bytes.
/// The output pointers must reference writable buffers of exactly 64, 128, and 64 bytes.
#[no_mangle]
pub unsafe extern "C" fn decompress_proof_to_solana_coords(
    proof_a_comp_ptr: *const u8,
    proof_b_comp_ptr: *const u8,
    proof_c_comp_ptr: *const u8,
    proof_a_uncomp_out_ptr: *mut u8,
    proof_b_uncomp_out_ptr: *mut u8,
    proof_c_uncomp_out_ptr: *mut u8,
) -> u32 {
    let proof_a_comp = unsafe { std::slice::from_raw_parts(proof_a_comp_ptr, 32) };
    let proof_b_comp = unsafe { std::slice::from_raw_parts(proof_b_comp_ptr, 64) };
    let proof_c_comp = unsafe { std::slice::from_raw_parts(proof_c_comp_ptr, 32) };

    let p_a = match ark_bn254::G1Affine::deserialize_compressed(proof_a_comp) {
        Ok(p) => p,
        Err(_) => return 0,
    };
    let p_b = match ark_bn254::G2Affine::deserialize_compressed(proof_b_comp) {
        Ok(p) => p,
        Err(_) => return 0,
    };
    let p_c = match ark_bn254::G1Affine::deserialize_compressed(proof_c_comp) {
        Ok(p) => p,
        Err(_) => return 0,
    };

    let solana_a = to_solana_g1(&p_a);
    let solana_b = to_solana_g2(&p_b);
    let solana_c = to_solana_g1(&p_c);

    unsafe {
        std::ptr::copy_nonoverlapping(solana_a.as_ptr(), proof_a_uncomp_out_ptr, 64);
        std::ptr::copy_nonoverlapping(solana_b.as_ptr(), proof_b_uncomp_out_ptr, 128);
        std::ptr::copy_nonoverlapping(solana_c.as_ptr(), proof_c_uncomp_out_ptr, 64);
    }

    1
}

#[cfg(test)]
mod verifier_key_tests {
    use super::*;

    #[test]
    fn missing_verifying_key_fails_closed() {
        let unique = format!(
            "zymatica_missing_vk_{}_{}.bin",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock must be after Unix epoch")
                .as_nanos()
        );
        let path = std::env::temp_dir().join(unique);
        assert!(!path.exists());
        assert!(load_vk_from_path(&path).is_err());
    }
}
